BEGIN;
SELECT plan(74);
SELECT todo('Two regexp need fix', 2);
SELECT ok(hn_ranker.is_url('http://foo.com/blah_blah'),'http://foo.com/blah_blah');
SELECT ok(hn_ranker.is_url('http://foo.com/blah_blah/'),'http://foo.com/blah_blah/');
SELECT ok(hn_ranker.is_url('http://foo.com/blah_blah_(wikipedia)'),'http://foo.com/blah_blah_(wikipedia)');
SELECT ok(hn_ranker.is_url('http://foo.com/blah_blah_(wikipedia)_(again)'),'http://foo.com/blah_blah_(wikipedia)_(again)');
SELECT ok(hn_ranker.is_url('http://www.example.com/wpstyle/?p=364'),'http://www.example.com/wpstyle/?p=364');
SELECT ok(hn_ranker.is_url('https://www.example.com/foo/?bar=baz&inga=42&quux'),'https://www.example.com/foo/?bar=baz&inga=42&quux');
SELECT ok(hn_ranker.is_url('http://✪df.ws/123'),'http://✪df.ws/123');
SELECT ok(hn_ranker.is_url('http://userid:password@example.com:8080'),'http://userid:password@example.com:8080');
SELECT ok(hn_ranker.is_url('http://userid:password@example.com:8080/'),'http://userid:password@example.com:8080/');
SELECT ok(hn_ranker.is_url('http://userid@example.com'),'http://userid@example.com');
SELECT ok(hn_ranker.is_url('http://userid@example.com/'),'http://userid@example.com/');
SELECT ok(hn_ranker.is_url('http://userid@example.com:8080'),'http://userid@example.com:8080');
SELECT ok(hn_ranker.is_url('http://userid@example.com:8080/'),'http://userid@example.com:8080/');
SELECT ok(hn_ranker.is_url('http://userid:password@example.com'),'http://userid:password@example.com');
SELECT ok(hn_ranker.is_url('http://userid:password@example.com/'),'http://userid:password@example.com/');
SELECT ok(hn_ranker.is_url('http://142.42.1.1/'),'http://142.42.1.1/');
SELECT ok(hn_ranker.is_url('http://142.42.1.1:8080/'),'http://142.42.1.1:8080/');
SELECT ok(hn_ranker.is_url('http://➡.ws/䨹'),'http://➡.ws/䨹');
SELECT ok(hn_ranker.is_url('http://⌘.ws'),'http://⌘.ws');
SELECT ok(hn_ranker.is_url('http://⌘.ws/'),'http://⌘.ws/');
SELECT ok(hn_ranker.is_url('http://foo.com/blah_(wikipedia)#cite-1'),'http://foo.com/blah_(wikipedia)#cite-1');
SELECT ok(hn_ranker.is_url('http://foo.com/blah_(wikipedia)_blah#cite-1'),'http://foo.com/blah_(wikipedia)_blah#cite-1');
SELECT ok(hn_ranker.is_url('http://foo.com/unicode_(✪)_in_parens'),'http://foo.com/unicode_(✪)_in_parens');
SELECT ok(hn_ranker.is_url('http://foo.com/(something)?after=parens'),'http://foo.com/(something)?after=parens');
SELECT ok(hn_ranker.is_url('http://☺.damowmow.com/'),'http://☺.damowmow.com/');
SELECT ok(hn_ranker.is_url('http://code.google.com/events/#&product=browser'),'http://code.google.com/events/#&product=browser');
SELECT ok(hn_ranker.is_url('http://j.mp'),'http://j.mp');
SELECT ok(hn_ranker.is_url('ftp://foo.bar/baz'),'ftp://foo.bar/baz');
SELECT ok(hn_ranker.is_url('http://foo.bar/?q=Test%20URL-encoded%20stuff'),'http://foo.bar/?q=Test%20URL-encoded%20stuff');
SELECT ok(hn_ranker.is_url('http://مثال.إختبار'),'http://مثال.إختبار');
SELECT ok(hn_ranker.is_url('http://例子.测试'),'http://例子.测试');
SELECT ok(hn_ranker.is_url('http://उदाहरण.परीक्षा'),'http://उदाहरण.परीक्षा');
SELECT ok(hn_ranker.is_url('http://-.~_!$&''()*+,;=:%40:80%2f::::::@example.com'),'http://-.~_!$&''()*+,;=:%40:80%2f::::::@example.com');
SELECT ok(hn_ranker.is_url('http://1337.net'),'http://1337.net');
SELECT ok(hn_ranker.is_url('http://a.b-c.de'),'http://a.b-c.de');
SELECT ok(hn_ranker.is_url('http://223.255.255.254'),'http://223.255.255.254');
SELECT ok(hn_ranker.is_url('http://') = false,'http://');
SELECT ok(hn_ranker.is_url('http://.') = false,'http://.');
SELECT ok(hn_ranker.is_url('http://..') = false,'http://..');
SELECT ok(hn_ranker.is_url('http://../') = false,'http://../');
SELECT ok(hn_ranker.is_url('http://?') = false,'http://?');
SELECT ok(hn_ranker.is_url('http://??') = false,'http://??');
SELECT ok(hn_ranker.is_url('http://??/') = false,'http://??/');
SELECT ok(hn_ranker.is_url('http://#') = false,'http://#');
SELECT ok(hn_ranker.is_url('http://##') = false,'http://##');
SELECT ok(hn_ranker.is_url('http://##/') = false,'http://##/');
SELECT ok(hn_ranker.is_url('http://foo.bar?q=Spaces should be encoded') = false,'http://foo.bar?q=Spaces should be encoded');
SELECT ok(hn_ranker.is_url('//') = false,'//');
SELECT ok(hn_ranker.is_url('//a') = false,'//a');
SELECT ok(hn_ranker.is_url('///a') = false,'///a');
SELECT ok(hn_ranker.is_url('///') = false,'///');
SELECT ok(hn_ranker.is_url('http:///a') = false,'http:///a');
SELECT ok(hn_ranker.is_url('foo.com') = false,'foo.com');
SELECT ok(hn_ranker.is_url('rdar://1234') = false,'rdar://1234');
SELECT ok(hn_ranker.is_url('h://test') = false,'h://test');
SELECT ok(hn_ranker.is_url('http:// shouldfail.com') = false,'http:// shouldfail.com');
SELECT ok(hn_ranker.is_url(':// should fail') = false,':// should fail');
SELECT ok(hn_ranker.is_url('http://foo.bar/foo(bar)baz quux') = false,'http://foo.bar/foo(bar)baz quux');
SELECT ok(hn_ranker.is_url('ftps://foo.bar/') = false,'ftps://foo.bar/');
SELECT ok(hn_ranker.is_url('http://-error-.invalid/') = false,'http://-error-.invalid/');
SELECT todo_start( 'Should fail' );
SELECT ok(hn_ranker.is_url('http://a.b--c.de/') = false,'http://a.b--c.de/');
SELECT todo_end();
SELECT ok(hn_ranker.is_url('http://-a.b.co') = false,'http://-a.b.co');
SELECT ok(hn_ranker.is_url('http://a.b-.co') = false,'http://a.b-.co');
SELECT ok(hn_ranker.is_url('http://0.0.0.0') = false,'http://0.0.0.0');
SELECT ok(hn_ranker.is_url('http://10.1.1.0') = false,'http://10.1.1.0');
SELECT ok(hn_ranker.is_url('http://10.1.1.255') = false,'http://10.1.1.255');
SELECT ok(hn_ranker.is_url('http://224.1.1.1') = false,'http://224.1.1.1');
SELECT ok(hn_ranker.is_url('http://1.1.1.1.1') = false,'http://1.1.1.1.1');
SELECT ok(hn_ranker.is_url('http://123.123.123') = false,'http://123.123.123');
SELECT ok(hn_ranker.is_url('http://3628126748') = false,'http://3628126748');
SELECT ok(hn_ranker.is_url('http://.www.foo.bar/') = false,'http://.www.foo.bar/');
SELECT todo_start( 'Should fail' );
SELECT ok(hn_ranker.is_url('http://www.foo.bar./') = false,'http://www.foo.bar./');
SELECT todo_end();
SELECT ok(hn_ranker.is_url('http://.www.foo.bar./') = false,'http://.www.foo.bar./');
SELECT ok(hn_ranker.is_url('http://10.1.1.1') = false,'http://10.1.1.1');
SELECT * FROM finish();
ROLLBACK;
