BEGIN;
SELECT plan(74);
SELECT todo('Two regexp need fix', 2);
SELECT lives_ok($$SELECT 'http://foo.com/blah_blah'::hn_ranker.url;$$,'http://foo.com/blah_blah');
SELECT lives_ok($$SELECT 'http://foo.com/blah_blah/'::hn_ranker.url;$$,'http://foo.com/blah_blah/');
SELECT lives_ok($$SELECT 'http://foo.com/blah_blah_(wikipedia)'::hn_ranker.url;$$,'http://foo.com/blah_blah_(wikipedia)');
SELECT lives_ok($$SELECT 'http://foo.com/blah_blah_(wikipedia)_(again)'::hn_ranker.url;$$,'http://foo.com/blah_blah_(wikipedia)_(again)');
SELECT lives_ok($$SELECT 'http://www.example.com/wpstyle/?p=364'::hn_ranker.url;$$,'http://www.example.com/wpstyle/?p=364');
SELECT lives_ok($$SELECT 'https://www.example.com/foo/?bar=baz&inga=42&quux'::hn_ranker.url;$$,'https://www.example.com/foo/?bar=baz&inga=42&quux');
SELECT lives_ok($$SELECT 'http://✪df.ws/123'::hn_ranker.url;$$,'http://✪df.ws/123');
SELECT lives_ok($$SELECT 'http://userid:password@example.com:8080'::hn_ranker.url;$$,'http://userid:password@example.com:8080');
SELECT lives_ok($$SELECT 'http://userid:password@example.com:8080/'::hn_ranker.url;$$,'http://userid:password@example.com:8080/');
SELECT lives_ok($$SELECT 'http://userid@example.com'::hn_ranker.url;$$,'http://userid@example.com');
SELECT lives_ok($$SELECT 'http://userid@example.com/'::hn_ranker.url;$$,'http://userid@example.com/');
SELECT lives_ok($$SELECT 'http://userid@example.com:8080'::hn_ranker.url;$$,'http://userid@example.com:8080');
SELECT lives_ok($$SELECT 'http://userid@example.com:8080/'::hn_ranker.url;$$,'http://userid@example.com:8080/');
SELECT lives_ok($$SELECT 'http://userid:password@example.com'::hn_ranker.url;$$,'http://userid:password@example.com');
SELECT lives_ok($$SELECT 'http://userid:password@example.com/'::hn_ranker.url;$$,'http://userid:password@example.com/');
SELECT lives_ok($$SELECT 'http://142.42.1.1/'::hn_ranker.url;$$,'http://142.42.1.1/');
SELECT lives_ok($$SELECT 'http://142.42.1.1:8080/'::hn_ranker.url;$$,'http://142.42.1.1:8080/');
SELECT lives_ok($$SELECT 'http://➡.ws/䨹'::hn_ranker.url;$$,'http://➡.ws/䨹');
SELECT lives_ok($$SELECT 'http://⌘.ws'::hn_ranker.url;$$,'http://⌘.ws');
SELECT lives_ok($$SELECT 'http://⌘.ws/'::hn_ranker.url;$$,'http://⌘.ws/');
SELECT lives_ok($$SELECT 'http://foo.com/blah_(wikipedia)#cite-1'::hn_ranker.url;$$,'http://foo.com/blah_(wikipedia)#cite-1');
SELECT lives_ok($$SELECT 'http://foo.com/blah_(wikipedia)_blah#cite-1'::hn_ranker.url;$$,'http://foo.com/blah_(wikipedia)_blah#cite-1');
SELECT lives_ok($$SELECT 'http://foo.com/unicode_(✪)_in_parens'::hn_ranker.url;$$,'http://foo.com/unicode_(✪)_in_parens');
SELECT lives_ok($$SELECT 'http://foo.com/(something)?after=parens'::hn_ranker.url;$$,'http://foo.com/(something)?after=parens');
SELECT lives_ok($$SELECT 'http://☺.damowmow.com/'::hn_ranker.url;$$,'http://☺.damowmow.com/');
SELECT lives_ok($$SELECT 'http://code.google.com/events/#&product=browser'::hn_ranker.url;$$,'http://code.google.com/events/#&product=browser');
SELECT lives_ok($$SELECT 'http://j.mp'::hn_ranker.url;$$,'http://j.mp');
SELECT lives_ok($$SELECT 'ftp://foo.bar/baz'::hn_ranker.url;$$,'ftp://foo.bar/baz');
SELECT lives_ok($$SELECT 'http://foo.bar/?q=Test%20URL-encoded%20stuff'::hn_ranker.url;$$,'http://foo.bar/?q=Test%20URL-encoded%20stuff');
SELECT lives_ok($$SELECT 'http://مثال.إختبار'::hn_ranker.url;$$,'http://مثال.إختبار');
SELECT lives_ok($$SELECT 'http://例子.测试'::hn_ranker.url;$$,'http://例子.测试');
SELECT lives_ok($$SELECT 'http://उदाहरण.परीक्षा'::hn_ranker.url;$$,'http://उदाहरण.परीक्षा');
SELECT lives_ok($$SELECT 'http://-.~_!$&''()*+,;=:%40:80%2f::::::@example.com'::hn_ranker.url;$$,'http://-.~_!$&''()*+,;=:%40:80%2f::::::@example.com');
SELECT lives_ok($$SELECT 'http://1337.net'::hn_ranker.url;$$,'http://1337.net');
SELECT lives_ok($$SELECT 'http://a.b-c.de'::hn_ranker.url;$$,'http://a.b-c.de');
SELECT lives_ok($$SELECT 'http://223.255.255.254'::hn_ranker.url;$$,'http://223.255.255.254');
SELECT throws_ok($$SELECT 'http://'::hn_ranker.url;$$,23514,NULL,'http://');
SELECT throws_ok($$SELECT 'http://.'::hn_ranker.url;$$,23514,NULL,'http://.');
SELECT throws_ok($$SELECT 'http://..'::hn_ranker.url;$$,23514,NULL,'http://..');
SELECT throws_ok($$SELECT 'http://../'::hn_ranker.url;$$,23514,NULL,'http://../');
SELECT throws_ok($$SELECT 'http://?'::hn_ranker.url;$$,23514,NULL,'http://?');
SELECT throws_ok($$SELECT 'http://??'::hn_ranker.url;$$,23514,NULL,'http://??');
SELECT throws_ok($$SELECT 'http://??/'::hn_ranker.url;$$,23514,NULL,'http://??/');
SELECT throws_ok($$SELECT 'http://#'::hn_ranker.url;$$,23514,NULL,'http://#');
SELECT throws_ok($$SELECT 'http://##'::hn_ranker.url;$$,23514,NULL,'http://##');
SELECT throws_ok($$SELECT 'http://##/'::hn_ranker.url;$$,23514,NULL,'http://##/');
SELECT throws_ok($$SELECT 'http://foo.bar?q=Spaces should be encoded'::hn_ranker.url;$$,23514,NULL,'http://foo.bar?q=Spaces should be encoded');
SELECT throws_ok($$SELECT '//'::hn_ranker.url;$$,23514,NULL,'//');
SELECT throws_ok($$SELECT '//a'::hn_ranker.url;$$,23514,NULL,'//a');
SELECT throws_ok($$SELECT '///a'::hn_ranker.url;$$,23514,NULL,'///a');
SELECT throws_ok($$SELECT '///'::hn_ranker.url;$$,23514,NULL,'///');
SELECT throws_ok($$SELECT 'http:///a'::hn_ranker.url;$$,23514,NULL,'http:///a');
SELECT throws_ok($$SELECT 'foo.com'::hn_ranker.url;$$,23514,NULL,'foo.com');
SELECT throws_ok($$SELECT 'rdar://1234'::hn_ranker.url;$$,23514,NULL,'rdar://1234');
SELECT throws_ok($$SELECT 'h://test'::hn_ranker.url;$$,23514,NULL,'h://test');
SELECT throws_ok($$SELECT 'http:// shouldfail.com'::hn_ranker.url;$$,23514,NULL,'http:// shouldfail.com');
SELECT throws_ok($$SELECT ':// should fail'::hn_ranker.url;$$,23514,NULL,':// should fail');
SELECT throws_ok($$SELECT 'http://foo.bar/foo(bar)baz quux'::hn_ranker.url;$$,23514,NULL,'http://foo.bar/foo(bar)baz quux');
SELECT throws_ok($$SELECT 'ftps://foo.bar/'::hn_ranker.url;$$,23514,NULL,'ftps://foo.bar/');
SELECT throws_ok($$SELECT 'http://-error-.invalid/'::hn_ranker.url;$$,23514,NULL,'http://-error-.invalid/');
SELECT todo_start( 'Should fail' );
SELECT throws_ok($$SELECT 'http://a.b--c.de/'::hn_ranker.url;$$,23514,NULL,'http://a.b--c.de/');
SELECT todo_end();
SELECT throws_ok($$SELECT 'http://-a.b.co'::hn_ranker.url;$$,23514,NULL,'http://-a.b.co');
SELECT throws_ok($$SELECT 'http://a.b-.co'::hn_ranker.url;$$,23514,NULL,'http://a.b-.co');
SELECT throws_ok($$SELECT 'http://0.0.0.0'::hn_ranker.url;$$,23514,NULL,'http://0.0.0.0');
SELECT throws_ok($$SELECT 'http://10.1.1.0'::hn_ranker.url;$$,23514,NULL,'http://10.1.1.0');
SELECT throws_ok($$SELECT 'http://10.1.1.255'::hn_ranker.url;$$,23514,NULL,'http://10.1.1.255');
SELECT throws_ok($$SELECT 'http://224.1.1.1'::hn_ranker.url;$$,23514,NULL,'http://224.1.1.1');
SELECT throws_ok($$SELECT 'http://1.1.1.1.1'::hn_ranker.url;$$,23514,NULL,'http://1.1.1.1.1');
SELECT throws_ok($$SELECT 'http://123.123.123'::hn_ranker.url;$$,23514,NULL,'http://123.123.123');
SELECT throws_ok($$SELECT 'http://3628126748'::hn_ranker.url;$$,23514,NULL,'http://3628126748');
SELECT throws_ok($$SELECT 'http://.www.foo.bar/'::hn_ranker.url;$$,23514,NULL,'http://.www.foo.bar/');
SELECT todo_start( 'Should fail' );
SELECT throws_ok($$SELECT 'http://www.foo.bar./'::hn_ranker.url;$$,23514,NULL,'http://www.foo.bar./');
SELECT todo_end();
SELECT throws_ok($$SELECT 'http://.www.foo.bar./'::hn_ranker.url;$$,23514,NULL,'http://.www.foo.bar./');
SELECT throws_ok($$SELECT 'http://10.1.1.1'::hn_ranker.url;$$,23514,NULL,'http://10.1.1.1');
SELECT * FROM finish();
ROLLBACK;
